# Generated by Django 3.0.4 on 2020-04-10 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='line_total',
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='quantity',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
