# Generated by Django 3.0.4 on 2020-04-02 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0003_auto_20200401_1615'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='delivery_cost',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=200),
        ),
    ]
