# Generated by Django 3.0.4 on 2020-04-02 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0004_cart_delivery_cost'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='cart_total',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=200),
        ),
        migrations.AddField(
            model_name='cart',
            name='products_total',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=200),
        ),
    ]
