# Generated by Django 2.2.5 on 2020-04-17 12:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Nazwa')),
                ('description', models.CharField(blank=True, max_length=240, null=True, verbose_name='Opis')),
                ('category', models.CharField(choices=[('Vegetables', 'Warzywa'), ('Fruits', 'Owoce'), ('Spices', 'Zioła i przyprawy'), ('Other', 'Inne')], default='Warzywa', max_length=120, verbose_name='Kategoria')),
                ('min_qty_value', models.FloatField(verbose_name='Min ilość')),
                ('min_qty_info', models.CharField(choices=[('kg', 'kg'), ('g', 'g'), ('pcs', 'szt'), ('pack', 'op'), ('liter', 'l')], default='kg', max_length=120, verbose_name='Min waga')),
                ('net_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=20, verbose_name='Netto')),
                ('vat', models.FloatField(default=0.05, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)], verbose_name='VAT')),
                ('active', models.BooleanField(default=True, verbose_name='Aktywny')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='Zdjęcie')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Ostatnia zmiana')),
            ],
        ),
    ]
