# Generated by Django 3.0.4 on 2020-04-06 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20200405_1229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Vegetables', 'Warzywa'), ('Fruits', 'Owoce'), ('Spices', 'Zioła i przyprawy'), ('Other', 'Inne')], default='Warzywa', max_length=120),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.CharField(blank=True, max_length=240, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='min_qty_info',
            field=models.CharField(choices=[('kg', 'kg'), ('g', 'g'), ('pcs', 'szt'), ('pack', 'op'), ('liter', 'l')], default='kg', max_length=120),
        ),
    ]
