# Generated by Django 3.0.4 on 2020-04-07 16:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_auto_20200406_1128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Aktywny'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Vegetables', 'Warzywa'), ('Fruits', 'Owoce'), ('Spices', 'Zioła i przyprawy'), ('Other', 'Inne')], default='Warzywa', max_length=120, verbose_name='Kategoria'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.CharField(blank=True, max_length=240, null=True, verbose_name='Opis'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='Zdjęcie'),
        ),
        migrations.AlterField(
            model_name='product',
            name='min_qty_info',
            field=models.CharField(choices=[('kg', 'kg'), ('g', 'g'), ('pcs', 'szt'), ('pack', 'op'), ('liter', 'l')], default='kg', max_length=120, verbose_name='Min waga'),
        ),
        migrations.AlterField(
            model_name='product',
            name='min_qty_value',
            field=models.FloatField(default=1, verbose_name='Min ilość'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=120, verbose_name='Nazwa'),
        ),
        migrations.AlterField(
            model_name='product',
            name='net_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=20, verbose_name='Netto'),
        ),
        migrations.AlterField(
            model_name='product',
            name='vat',
            field=models.FloatField(default=0.05, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)], verbose_name='VAT'),
        ),
    ]
