# Generated by Django 3.0.4 on 2020-03-30 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_auto_20200330_1724'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='min_qty_info',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='product',
            name='min_qty_value',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='net_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='vat',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
