# Generated by Django 3.0.4 on 2020-03-30 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_auto_20200330_1756'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='net_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=20),
        ),
    ]
