# Generated by Django 3.0.4 on 2020-04-10 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_auto_20200407_1825'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='min_qty_value',
            field=models.FloatField(verbose_name='Min ilość'),
        ),
        migrations.AlterField(
            model_name='product',
            name='updated',
            field=models.DateTimeField(auto_now=True, verbose_name='Ostatnia zmiana'),
        ),
    ]
