# Generated by Django 3.0.4 on 2020-04-02 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=2000),
        ),
        migrations.AddField(
            model_name='order',
            name='order_total',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=2000),
        ),
        migrations.AddField(
            model_name='order',
            name='products_total',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=2000),
        ),
    ]
